version: '3.8'

networks:
  traefik-network:
    external: true
    name: traefik-network
  symonds:
    name: symonds

volumes:
  db:
    driver: local
  redis:
    driver: local

services:
  symonds-fpm:
    env_file: ../app/.env
    environment:
      - CONTAINER_ROLE=fpm
      - PHP_OPCACHE_ENABLED=0
      - PHP_MEMORY_LIMIT=2048M
      - PM_MAX_CHILDREN=5
      - PM_START_SERVERS=1
      - PM_MIN_SPARE_SERVERS=1
      - PM_MAX_SPARE_SERVERS=2
      - PM_MAX_REQUEST=300
    build:
      context: ../
      dockerfile: build/php/Dockerfile
      target: php
    volumes:
      - ../app:/app
    networks:
      - symonds
  nginx:
    env_file: ../app/.env
    build:
      context: ../
      dockerfile: build/nginx/Dockerfile
      target: nginx
    labels:
      - traefik.http.routers.symonds-admin.rule=Host(`crm.symonds.localhost`)
      - traefik.http.routers.symonds-admin.tls=true
      - traefik.http.routers.symonds-admin.entrypoints=websecure
      - traefik.http.services.symonds-admin.loadbalancer.server.port=80
      - traefik.enable=true
    volumes:
      - ../app:/app
    depends_on:
      - symonds-fpm
      - mysql
      - redis
    networks:
      - symonds
      - traefik-network
  mysql:
    image: mysql:8.0
    env_file: ../app/.env
    restart: always
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - symonds
      - traefik-network
  redis:
    image: redis:7.0-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis:/data
    networks:
      - symonds
      - traefik-network
